name: Convert MKV to MP4 and Upload to Google Drive

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        python3 -m pip install --upgrade pip
        python3 -m pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Create token.pickle
      run: |
        echo "${{ secrets.GDRIVE_TOKEN }}" | base64 --decode > token.pickle

    - name: Download MKV file
      run: |
        curl -L -o video.mkv "https://sxtcp.tg-index.workers.dev/0:/drakor/little.women/Little.Women.S01E03.Episode.3.720p.NF.WEB-DL.x265.10Bit-Pahe.li.mkv"

    - name: Convert MKV to MP4
      run: |
        ffmpeg -i video.mkv -vf "scale=1280:720,subtitles=video.mkv:si=2" -r 24 -c:v libx264 -preset fast -crf 22 -c:a aac -b:a 160k -ac 2 -movflags +faststart video.mp4



    - name: Upload to Google Drive
      run: python3 upload_to_gdrive.py video.mp4
